language: python
cache: pip
dist: trusty
python:
  - "3.6"

before_install:
  - pip install pip --upgrade
  - pip install pytest --upgrade  # needed to update default pytest

install:
  - pip install -e .[test]

script:
  - pytest --cov -rfsxEX

after_success:
  - codecov
